### ISSUE TITLE
Add support for IntelliJ IDEA 2024.2

### ISSUE THREAD

**Issue by ofry** [niftythoughts/ansi-highlighter-premium#17]
ANSI Highlighter Premium 24.1.0

Compatibility Range
241—241.* (2024.1 — 2024.1.5)

```
IntelliJ IDEA 2024.2 (Ultimate Edition)
Build #IU-242.20224.300, built on August 6, 2024
```

**Comment by jordanburke** [comment]
@niftythoughts please fix this asap. It's been weeks now and some of us have paid for it. Thank you.

**Comment by kpervin** [comment]
Is there any plan for this?

**Comment by emilyst** [comment]
This problem has happened a couple of times this year alone (see also #16). I paid for this plugin specifically to avoid the problems of abandonware, but it sounds like I'll need to find another replacement.

**Comment by jordanburke** [comment]
Yeah I already requested and got it refunded a week or so ago via JetBrains. Too bad. Hopefully nothing happened to the developer, but it would have been helpful if there were more contact options regardless.

**Comment by oldium** [comment]
Discontinuing product development is one thing, but supporting paying customers is something completely different. It's a shame that the author decided to end the support for paying customers too, effectively making it impossible for everyone to use the rest of the paid subscription period.

**Comment by niftythoughts** [comment]
I sincerely apologize for the delay in addressing this issue. The updated version of the plugin has now been submitted and is currently pending JetBrains' approval.

I would also like to clarify a few important points moving forward:

- The payment for the new version guarantees support only for the current version of the IDE. Support for future IDE versions may be delayed or not provided at all.

- Unfortunately, due to JetBrains' policies that restrict plugin exposure to end users, it has become difficult to keep up with the frequent updates and API deprecations that directly affect the functionality of our plugin. Our original vision was to maintain a low price for users while ensuring a sustainable revenue stream based on sales volume. This approach would have enabled us to fund ongoing maintenance and support, creating a win-win situation for end-users, Nifty Thoughts, and JetBrains alike.

- JetBrains has chosen to block this model by blocking our plugin exposure to its target audience, providing no reasonable justification for their decision. This has severely impacted our motivation and dedication to maintain the plugin.

- As a result, future support for later IDE versions is uncertain. While we may provide updates, we cannot guarantee them, so please be aware that your purchase only guarantees perpetual support for the current IDE version.

More context  [here](https://youtrack.jetbrains.com/issue/IJPL-7483)

**Comment by oldium** [comment]
I do not want to sound silly, but it looks like that when I buy a 1-year license I will get a software usable for 1 week or 1 month depending on when the next release comes out. Right? If there is no guarantee to actually be able to use the software, it does not make sense to buy it. I actually stopped the renewal because of the missing support from Nifty Thoughts, not because of JetBrains actions.

**Comment by oldium** [comment]
> > I do not want to sound silly, but it looks like that when I buy a 1-year license I will get a software usable for 1 week or 1 month depending on when the next release comes out. Right? If there is no guarantee to actually be able to use the software, it does not make sense to buy it. I actually stopped the renewal because of the missing support from Nifty Thoughts, not because of JetBrains actions.
> 
> You stopped renewal because of the missing support from Nifty Thoughts, but Nifty Thoughts missing support is directly linked to JetBrains actions.

I would understand if you stopped offering to buy new licences because of your argument with Jetbrains, where I am entitely on your side. But not supporting already paying customers is purely your decision and has nothing to do with Jetbrains.

**Comment by niftythoughts** [comment]
A new version with support for 2024.2 was submitted on October 19th and is currently pending JetBrains' approval. We'll wait for their decision on whether the plugin remains available.

Moving forward, we’ve made it clear on the plugin page that we do not guarantee timely support for future IDE versions. If you tend to adopt new IDE releases as soon as they are available, ANSI Highlighter may not be the right fit for you. However, if you generally prefer holding off on immediate IDE updates, you can decide whether the plugin is worth the $5 price.

**Comment by oldium** [comment]
I think most of us have automatic updates enabled. So this is not about "adopting new IDE releases as soon as they are available". I do not care. It updates by itself and I am fine with it.

**Comment by oldium** [comment]
But I don't want to unnecessarily spike the discussion, it's your decision, that's completely fine and I accept it completely. Have a nice day.

**Comment by niftythoughts** [comment]
Sorry to disappoint you. However, maintaining the plugin for the $5 price point is far more challenging than it may appear. It would have been possible to sustain if the plugin could reach its target audience, but as you already know this is unfortunately not the case.

At this stage, we see two possible paths:

- We could remove the plugin entirely—this is something we would consider if there’s enough demand for it. There's even a chance that JB bans it after our latest comment on the plugin page, if that is their decision then it's on them.

- We continue to provide updates at our own pace. For now, we believe this is the best compromise to ensure the plugin remains available for users who don't mind it.

Thank you for your understanding, and I appreciate your feedback.

**Comment by niftythoughts** [comment]
[2024.2.0](https://plugins.jetbrains.com/plugin/9707-ansi-highlighter-premium/versions/stable/621172) has been approved

**Comment by niftythoughts** [comment]
<img width="800" alt="Screenshot 2024-11-04 at 12 26 56 AM" src="https://github.com/user-attachments/assets/5064edf0-ffd7-4b6a-a81a-8fb0788011b3">

**Comment by danny-su** [comment]
@niftythoughts Great, I will resume my subscription.

**Comment by oldium** [comment]
> @niftythoughts Great, I will resume my subscription.

I did that to. 👍
