### ISSUE TITLE
Invalid?

### ISSUE THREAD

**Issue by gudstrand** [niftythoughts/ansi-highlighter-premium#9]
![CleanShot 2023-04-10 at 12 21 19@2x](https://user-images.githubusercontent.com/70268/230955821-c2b77833-744b-470b-bb99-c453f360e215.png)

![CleanShot 2023-04-10 at 12 22 45@2x](https://user-images.githubusercontent.com/70268/230955915-e67ee9c8-7332-427c-a84b-ad486dcde751.png)

![CleanShot 2023-04-10 at 12 23 12@2x](https://user-images.githubusercontent.com/70268/230956009-f122dac5-0345-4325-ab15-e0e52b36f309.png)

**Comment by gudstrand** [comment]
I also opened an issue with the author of Noctumsempra's Color MEGAPACK.

**Comment by niftythoughts** [comment]
The issue is caused by 'Noctumsempra's Color MEGAPACK', it has nothing to do with ANSI Highlighter.

You have/had it at some point and it somehow corrupted your IDE setup... why did you deny then delete your comment?
<img width="641" alt="Screen Shot 2023-04-10 at 6 52 57 PM" src="https://user-images.githubusercontent.com/104358007/230960681-8ff62d1b-eb7e-46d3-aad8-7f2a589bbd60.png">

**Comment by gudstrand** [comment]
Wow, you seem really worked up. I edited my comment when I went back and found that I did have it installed. It is very strange that you would go and dig up a deleted comment and then attempt to state that I was doing something nefarious. LOL. 

The only reason I sent this error your way was because the dialog that comes up in Intellij says that it is an ANSI Highlighter issue. Doesn't it? BTW, my IDE setup is not corrupted. I use your plugin enough that i happily paid for a subscription. i was looking for some assistance. 

 I am sorry that you seem so agitated. Hope some joy finds you this day!  :-)

![CleanShot 2023-04-10 at 12 21 19@2x](https://user-images.githubusercontent.com/70268/230963914-afca1b7e-6139-4268-ba00-49292e18a38c.png)
